"""Window, world, and jam-friendly gameplay tuning."""

import pygame

WIDTH, HEIGHT = 1000, 700
# Pixel-art presentation
PIXEL_SCALE = 2

RENDER_WIDTH = WIDTH // PIXEL_SCALE
RENDER_HEIGHT = HEIGHT // PIXEL_SCALE
FPS = 60
WORLD_WIDTH, WORLD_HEIGHT = WIDTH, HEIGHT
CENTER = pygame.Vector2(WIDTH / 2, HEIGHT / 2)
SPAWN = pygame.Vector2(500, 440)
BOSS_SPAWN = pygame.Vector2(500, 145)
PLAYER_RADIUS = 12
BOSS_RADIUS = 62

# Original skating tuning: keep the prototype's momentum and carving feel.
MAX_SPEED = 520
ACCELERATION = 330
COAST_FRICTION = 0.15
BRAKE_FRICTION = 4.5
TURN_SPEED = 2.8
VELOCITY_CARVE_STRENGTH = 2.1

PLAYER_MAX_HP = 100
BOSS_MAX_HP = 850
MAX_STAMINA = 100
JUMP_COST = 15
DODGE_COST = 30
SLASH_COST = 10
JUMP_DURATION = 0.85
PARRY_WINDOW = 0.17
PARRY_RECOVERY = 0.34
DODGE_DURATION = 0.20
STAMINA_DELAY = 0.65
